// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klpuiqqyfemqzljqttnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtscHVpcXF5ZmVtcXpsanF0dG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDU0NDcsImV4cCI6MjA3MjUyMTQ0N30.69OXOIAsCvhS4rgJibGmlk9ipk-PesDJy9WLg5qwe6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});